# Generated by Django 4.2.6 on 2023-10-29 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifications',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, to='feed.followerrequest'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='likes',
            field=models.ManyToManyField(blank=True, to='post.postlike'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='post_comments',
            field=models.ManyToManyField(blank=True, to='post.comment'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='posts_liked',
            field=models.ManyToManyField(blank=True, to='post.post'),
        ),
        migrations.AddField(
            model_name='friends',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friends',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followerrequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followerrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_requester', to=settings.AUTH_USER_MODEL),
        ),
    ]
