# Generated by Django 4.2.6 on 2023-10-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notif_author_pfp',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notif_author_username',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
