# Generated by Django 4.2.6 on 2023-10-24 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_rename_feed_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='friend',
        ),
    ]
