# Generated by Django 4.2.6 on 2023-10-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_notifications_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='friend_pfp',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='friends',
            name='friend_username',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
