# Generated by Django 4.2.6 on 2023-11-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_friends_friend_pfp_friends_friend_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.CharField(choices=[('Liked your post', 'liked'), ('Commented on your post', 'commented'), ('Created a new post', 'posted')], max_length=200),
        ),
    ]
