# Generated by Django 4.2.6 on 2023-11-23 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_content_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0007_remove_notifications_id_notifications_notif_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('follow_requests', models.ManyToManyField(blank=True, to='feed.followerrequest')),
                ('notifications', models.ManyToManyField(blank=True, null=True, to='feed.notifications')),
                ('post_comments', models.ManyToManyField(blank=True, to='post.comment')),
                ('post_likes', models.ManyToManyField(blank=True, to='post.postlike')),
                ('posts', models.ManyToManyField(blank=True, to='post.post')),
            ],
        ),
    ]
