# Generated by Django 4.2.6 on 2023-11-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_alter_friends_friend_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='followerrequest',
            name='recipient_origin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='followerrequest',
            name='sender_origin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='friends',
            name='author_origin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='friends',
            name='friend_origin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_author_origin',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
