# Generated by Django 4.2.6 on 2023-11-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_followerrequest_recipient_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerrequest',
            name='recipient',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='followerrequest',
            name='sender',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='friends',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='friends',
            name='friend',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_author',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
