# Generated by Django 4.2.6 on 2023-11-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_alter_inbox_follow_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='follow_requests',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='post_comments',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='post_likes',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='posts',
            field=models.JSONField(blank=True),
        ),
    ]
