# Generated by Django 4.2.6 on 2023-11-26 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_alter_followerrequest_recipient_and_more'),
        ('feed', '0015_alter_inbox_follow_requests_and_more'),
    ]

    operations = [
    ]
