# Generated by Django 4.2.6 on 2023-10-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_appauthor_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appauthor',
            name='display_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='appauthor',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appauthor',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
