# Generated by Django 4.2.6 on 2023-10-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_appauthor_github_alter_appauthor_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appauthor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
