# Generated by Django 4.2.6 on 2023-10-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appauthor',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
