# Generated by Django 4.2.6 on 2023-10-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_appauthor_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appauthor',
            name='github',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='appauthor',
            name='url',
            field=models.URLField(blank=True, max_length=50),
        ),
    ]
