# Generated by Django 4.2.6 on 2023-10-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_origin_alter_post_source_alter_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'plaintext'), ('text/markdown', 'markdown')], default=('text/plain', 'plaintext'), max_length=200),
        ),
    ]
