# Generated by Django 4.2.6 on 2023-11-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
