# Generated by Django 4.2.6 on 2023-11-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
