# Generated by Django 4.2.6 on 2023-10-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_rename_image_post_image_file_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
