# Generated by Django 4.2.6 on 2023-12-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_comment_author_alter_postlike_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='author_origin',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
