# Generated by Django 4.2.6 on 2023-12-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_comment_author_origin_post_author_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_friends',
            field=models.BooleanField(default=False),
        ),
    ]
