# Generated by Django 4.2.6 on 2023-11-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_appauthor_image_url_alter_appauthor_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='appauthor',
            name='host',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appauthor',
            name='github',
            field=models.URLField(blank=True),
        ),
    ]
