# Generated by Django 4.2.6 on 2023-11-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_appauthor_host_alter_appauthor_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('group_url', models.CharField(blank=True, max_length=200, null=True)),
                ('auth_username', models.CharField(blank=True, max_length=200, null=True)),
                ('auth_password', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
