# Generated by Django 4.2.6 on 2023-11-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appauthor',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
