# Generated by Django 4.2.6 on 2023-10-23 05:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_appauthor_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appauthor',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
