# Generated by Django 4.2.6 on 2023-12-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_appauthor_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appauthor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
