# Generated by Django 4.2.6 on 2023-10-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_appauthor_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appauthor',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
