# Generated by Django 4.2.6 on 2023-10-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_appauthor_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appauthor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
